server:
  port: 8080

spring:
  application:
    name: course
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password:
      h2:
        console:
          enabled: true
          path: /h2-console
#  jpa:
#    show-sql: false
#    hibernate:
#      dll-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#  jmx:
#    enable: false
#  datasource:
#    url: jdbc://mysql://localhost:3306/devdojo?allowPublicKeyRetrieval=true&sslMode=DISABLED
#    username: root
#    password:devdojo